(() => {
  "use strict";

  const moduleHref = "organization-module.html";

  const catalog = [
    {
      id: "branch",
      title: "Branch Management",
      href: moduleHref,
      category: "Operations",
      componentRole: "Runs locations, local teams, stock movement, and branch performance.",
      description: "Locations, branch teams, local operations.",
      features: ["Branch records", "Local teams", "Operational scope"],
      sharedResources: ["Users", "Inventory", "Reports"],
    },
    {
      id: "departments",
      title: "Department Management",
      href: moduleHref,
      category: "Organization",
      componentRole: "Owns department structure, approvals, and internal workflow routing.",
      description: "Department users, workflows, and approvals.",
      features: ["Department roles", "Approvals", "Workflows"],
      sharedResources: ["Users", "Permissions", "Activity"],
    },
    {
      id: "hr",
      title: "HR Portal",
      href: moduleHref,
      category: "People",
      componentRole: "Owns employee records, attendance, leave, payroll preparation, schedules, contracts, and HR announcements.",
      description: "Employees, attendance, leave, payroll preparation, contracts, schedules, and performance reviews.",
      features: ["Employee records", "Payroll forwarding", "Leave approvals", "Attendance", "Documents", "Announcements"],
      sharedResources: ["Users", "Finance", "Permissions", "Reports"],
    },
    {
      id: "finance",
      title: "Finance Portal",
      href: moduleHref,
      category: "Finance",
      componentRole: "Approves payrolls and purchases, monitors transactions, tracks revenue, invoices, receipts, taxes, debt, payments, budgets, and profit.",
      description: "Revenue, payroll approvals, invoices, receipts, expenses, taxes, budgets, debts, payments, and financial reports.",
      features: ["Payroll approvals", "Invoices", "Budget tracking", "Profit reports", "PDF/Excel exports", "Debt tracking"],
      sharedResources: ["HR", "Procurement", "Sales", "Reports", "Analytics"],
    },
    {
      id: "pharmacy",
      title: "Pharmacy / Chemistry Portal",
      href: moduleHref,
      category: "Inventory",
      componentRole: "Controls medicine stock, prescriptions, expiry and low-stock alerts, suppliers, receipts, barcode lookup, returns, discounts, and pharmacist activity.",
      description: "Medicine inventory, prescriptions, suppliers, customers, barcode scanning, returns, discounts, and pharmacy sales.",
      features: ["Medicine stock", "Expiry alerts", "Prescriptions", "Barcode scan", "Supplier control", "Receipts"],
      sharedResources: ["Inventory", "Sales", "Finance", "Suppliers", "Reports"],
    },
    {
      id: "inventory",
      title: "Inventory Module",
      href: moduleHref,
      category: "Inventory",
      componentRole: "Controls stock, transfers, availability, and warehouse records.",
      description: "Stock, items, transfers, and availability.",
      features: ["Stock levels", "Transfers", "Availability"],
      sharedResources: ["Branches", "Reports", "Analytics"],
    },
    {
      id: "logistics",
      title: "Logistics Module",
      href: moduleHref,
      category: "Operations",
      componentRole: "Coordinates delivery, dispatch, fleet, and tracking workflows.",
      description: "Dispatch, delivery, fleet, and tracking workflows.",
      features: ["Dispatch", "Tracking", "Delivery status"],
      sharedResources: ["Orders", "Branches", "Activity"],
    },
    {
      id: "retail",
      title: "Retail Operations Module",
      href: moduleHref,
      category: "Industry",
      componentRole: "Runs POS activity, product catalog, shelf stock, customer purchases, returns, discounts, and daily retail reporting.",
      description: "Retail operations for shops, supermarkets, wholesalers, and multi-branch stores.",
      features: ["POS", "Returns", "Discounts", "Shelf stock", "Retail reports"],
      sharedResources: ["Sales", "Inventory", "Finance", "Customers"],
    },
    {
      id: "manufacturing",
      title: "Manufacturing Module",
      href: moduleHref,
      category: "Industry",
      componentRole: "Runs bills of materials, production orders, work centers, raw material usage, finished goods, quality checks, and production costing.",
      description: "Manufacturing operations for production, quality, materials, and costing.",
      features: ["Production orders", "BOM", "Work centers", "Quality checks", "Costing"],
      sharedResources: ["Inventory", "Procurement", "Finance", "Reports"],
    },
    {
      id: "sales",
      title: "Sales Portal",
      href: moduleHref,
      category: "Revenue",
      componentRole: "Owns products, customer orders, sales tracking, discounts, promotions, invoices, daily sales, and revenue analytics.",
      description: "Product management, orders, customers, invoices, discounts, daily reports, and revenue analytics.",
      features: ["Product management", "Order tracking", "Customer invoices", "Promotions", "Daily reports"],
      sharedResources: ["Customers", "Finance", "Analytics"],
    },
    {
      id: "procurement",
      title: "Procurement Portal",
      href: moduleHref,
      category: "Operations",
      componentRole: "Manages suppliers, purchase requests, purchase orders, delivery tracking, inventory requests, and finance approval routing.",
      description: "Supplier management, purchase requests, approvals, inventory requests, purchase orders, deliveries, and procurement reports.",
      features: ["Purchase requests", "Supplier records", "Purchase orders", "Delivery tracking", "Finance approvals"],
      sharedResources: ["Finance", "Inventory", "Suppliers", "Reports"],
    },
    {
      id: "technology",
      title: "Technology Services Portal",
      href: moduleHref,
      category: "Technology",
      componentRole: "Runs software projects, IT services, cybersecurity, hosting, SaaS subscriptions, deployments, support tickets, developer work, documentation, meetings, and client billing.",
      description: "Projects, team collaboration, clients, tasks, bugs, deployments, support tickets, developer management, meetings, files, documentation, invoices, subscriptions, and analytics.",
      features: ["Projects", "Bug tracking", "Deployments", "Service tickets", "Documentation", "Subscriptions"],
      sharedResources: ["Clients", "Finance", "Support", "Reports", "Analytics"],
    },
    {
      id: "analytics",
      title: "Analytics Module",
      href: moduleHref,
      category: "Insights",
      componentRole: "Reads shared module data and turns it into trends, charts, and insights.",
      description: "Realtime analytics, reports, and insights.",
      features: ["Charts", "Insights", "Activity trends"],
      sharedResources: ["Reports", "Activity", "All modules"],
    },
    {
      id: "admin",
      title: "Admin Portal",
      href: "organization-admin.html",
      category: "Control",
      componentRole: "Creates organizations, approves departments, manages users, permissions, subscriptions, settings, backups, security logs, analytics, and global announcements.",
      description: "Super admin controls, organizations, users, roles, permissions, system analytics, security logs, backups, subscriptions, and global settings.",
      features: ["Organizations", "Permissions", "Security logs", "Backups", "Subscriptions", "Global announcements"],
      sharedResources: ["Users", "Permissions", "Modules", "Audit"],
    },
    {
      id: "staff",
      title: "Staff Module",
      href: moduleHref,
      category: "People",
      componentRole: "Provides role-specific staff tasks and daily work views.",
      description: "Role-specific staff workspace.",
      features: ["Tasks", "Notifications", "Role access"],
      sharedResources: ["Users", "Notifications", "Activity"],
    },
    {
      id: "customer",
      title: "Customer Service Portal",
      href: moduleHref,
      category: "Service",
      componentRole: "Runs support tickets, complaints, live chat queues, feedback, issue escalation, service analytics, and customer communication.",
      description: "Customer tickets, complaints, live chat, feedback, escalation, and service analytics.",
      features: ["Support tickets", "Complaints", "Live chat", "Escalation", "Feedback analytics"],
      sharedResources: ["Sales", "Reports", "Activity", "Messaging"],
    },
    {
      id: "academic",
      title: "Academic / School Portal",
      href: moduleHref,
      category: "Education",
      componentRole: "Manages students, fees, attendance, exams, results, timetables, teachers, and parent communication for school organizations.",
      description: "Student registration, fee tracking, attendance, exams, results, timetables, teacher management, and parent communication.",
      features: ["Students", "Fees", "Exams", "Timetables", "Parent messages"],
      sharedResources: ["Finance", "HR", "Messaging", "Reports"],
    },
    {
      id: "hospital",
      title: "Hospital Portal",
      href: moduleHref,
      category: "Healthcare",
      componentRole: "Coordinates patient records, appointments, doctor schedules, prescriptions, billing, laboratory reports, nurse management, and emergency records.",
      description: "Patients, appointments, doctor schedules, prescriptions, billing, lab reports, nurses, and emergency records.",
      features: ["Patient records", "Appointments", "Prescriptions", "Billing", "Lab reports", "Emergency records"],
      sharedResources: ["Finance", "Pharmacy", "HR", "Reports"],
    },
    {
      id: "restaurant",
      title: "Restaurant Portal",
      href: moduleHref,
      category: "Hospitality",
      componentRole: "Runs order management, kitchen workflow, reservations, menu control, staff coordination, customer order tracking, and sales reporting.",
      description: "Orders, kitchen dashboard, reservations, menus, staff, sales reports, and customer order tracking.",
      features: ["Orders", "Kitchen dashboard", "Reservations", "Menu management", "Sales reports"],
      sharedResources: ["Inventory", "Sales", "HR", "Finance"],
    },
    {
      id: "real-estate",
      title: "Real Estate Portal",
      href: moduleHref,
      category: "Property",
      componentRole: "Manages property listings, tenants, rent collection, maintenance requests, property analytics, and payment records.",
      description: "Properties, tenants, rent tracking, maintenance requests, analytics, and payment records.",
      features: ["Property listings", "Tenants", "Rent tracking", "Maintenance", "Payment records"],
      sharedResources: ["Finance", "Customer Service", "Reports", "Messaging"],
    },
    {
      id: "reporting",
      title: "Reporting Module",
      href: moduleHref,
      category: "Insights",
      componentRole: "Combines operational, finance, and organization data into exportable reports.",
      description: "Operational, finance, and organization reports.",
      features: ["Operational reports", "Financial summaries", "Exports"],
      sharedResources: ["Finance", "Operations", "Analytics"],
    },
    {
      id: "director",
      title: "Executive ERP Portal",
      href: "Director.html",
      category: "Control",
      componentRole: "Gives executives multi-company oversight across branches, products, services, clients, finance, subscriptions, onboarding, and activity review.",
      description: "Executive review for multi-business ERP operations.",
      features: ["Executive reports", "Branch performance", "Subscription review", "Approval review"],
      sharedResources: ["Branches", "Finance", "Clients", "Analytics"],
    },
    {
      id: "device-branch",
      title: "Branch Operations Portal",
      href: "Branch.html",
      category: "Operations",
      componentRole: "Runs branch stock, service requests, product records, local sales, asset movement, and branch-level activity for any industry.",
      description: "Branch operations for products, services, stock, clients, and local sales.",
      features: ["Branch stock", "Service requests", "Product records", "Local sales"],
      sharedResources: ["Inventory", "Agents", "Finance", "Reports"],
    },
    {
      id: "team-leader",
      title: "Operations Lead Portal",
      href: "TeamLeader.html",
      category: "Operations",
      componentRole: "Assigns products, service jobs, onboarding tasks, and client portfolios to agents while tracking field team performance.",
      description: "Operations lead workspace for agent allocation, service assignment, and portfolio tracking.",
      features: ["Agent allocation", "Task assignment", "Service tracking", "Team performance"],
      sharedResources: ["Agents", "Inventory", "Clients", "Sales"],
    },
    {
      id: "agent",
      title: "ERP Agent Portal",
      href: "Agent.html",
      category: "Revenue",
      componentRole: "Registers organizations, manages clients, tracks onboarding, commissions, subscriptions, contracts, referrals, service requests, and reports across industries.",
      description: "Agent workspace for multi-industry ERP onboarding, client success, referrals, subscriptions, support, and branch operations.",
      features: ["Organization onboarding", "Client management", "Commissions", "Subscriptions", "Support requests", "Contracts"],
      sharedResources: ["Organizations", "Finance", "Customer Service", "Analytics"],
    },
    {
      id: "device-departments",
      title: "Department Workflow Portal",
      href: moduleHref,
      category: "Organization",
      componentRole: "Routes cross-department work through HR, finance, sales, operations, procurement, technology, and administration reviews.",
      description: "Department review for multi-business ERP workflows.",
      features: ["Department access", "Workflow review", "Approval pipelines", "Role control"],
      sharedResources: ["Users", "Finance", "Reports"],
    },
  ];

  const workflows = {
    branch: { title: "Branch Operations", labels: ["Branch", "Manager", "Performance", "Status"] },
    departments: { title: "Department Workflows", labels: ["Department", "Lead", "Workflow", "Approval"] },
    hr: { title: "HR Workforce Records", labels: ["Employee", "Department", "Attendance", "Payroll Status"] },
    finance: { title: "Finance Ledger", labels: ["Transaction", "Source", "Amount", "Approval Status"] },
    pharmacy: { title: "Pharmacy Stock", labels: ["Medicine", "Batch", "Expiry", "Stock"] },
    inventory: { title: "Inventory Control", labels: ["Item", "Warehouse", "Movement", "Quantity"] },
    logistics: { title: "Logistics Flow", labels: ["Shipment", "Driver/Fleet", "Route", "Status"] },
    retail: { title: "Retail Operations", labels: ["Sale/Return", "Register", "Amount", "Stock Impact"] },
    manufacturing: { title: "Production Control", labels: ["Production Order", "Work Center", "Material Status", "Quality"] },
    sales: { title: "Sales Pipeline", labels: ["Customer", "Order", "Value", "Invoice Status"] },
    procurement: { title: "Procurement Requests", labels: ["Request", "Supplier", "Amount", "Approval"] },
    technology: { title: "Technology Projects", labels: ["Project/Service", "Client", "Status", "Billing"] },
    analytics: { title: "Analytics Insights", labels: ["Metric", "Source", "Trend", "Action"] },
    admin: { title: "Admin Controls", labels: ["Setting", "Scope", "Owner", "Status"] },
    staff: { title: "Staff Tasks", labels: ["Task", "Assigned To", "Priority", "Status"] },
    customer: { title: "Customer Service", labels: ["Customer", "Issue", "Ticket", "Escalation"] },
    academic: { title: "Academic Records", labels: ["Student", "Class", "Fee Status", "Attendance"] },
    hospital: { title: "Hospital Operations", labels: ["Patient", "Service", "Doctor/Nurse", "Billing"] },
    restaurant: { title: "Restaurant Orders", labels: ["Order/Table", "Kitchen Status", "Server", "Payment"] },
    "real-estate": { title: "Property Operations", labels: ["Property", "Tenant", "Rent Status", "Maintenance"] },
    reporting: { title: "Reporting Center", labels: ["Report", "Scope", "Format", "Status"] },
  };

  const byId = Object.fromEntries(catalog.map((module) => [module.id, module]));

  window.EnterpriseModules = Object.freeze({
    catalog,
    workflows,
    validIds: new Set(catalog.map((module) => module.id)),
    get: (id) => byId[String(id || "").trim().toLowerCase()] || null,
    permissionsFor: (id) => [`${id}.read`, `${id}.manage`],
  });
})();
