const moduleHref = "organization-module.html";

const PORTAL_CATALOG = [
  { id: "admin", title: "Admin Portal", href: "organization-admin.html", category: "Control", description: "Organizations, users, permissions, subscriptions, settings, backups, security logs, and announcements.", features: ["Organizations", "Permissions", "Security logs", "Backups"] },
  { id: "branch", title: "Branch Management", href: moduleHref, category: "Operations", description: "Locations, warehouses, facilities, branch teams, and local operations.", features: ["Branch records", "Local teams", "Operational scope"] },
  { id: "departments", title: "Department Management", href: moduleHref, category: "Technology Services", package: "Phone Operations", description: "Phone service departments, roles, approvals, and workflow routing.", features: ["Phone departments", "Approvals", "Workflows"] },
  { id: "hr", title: "HR Portal", href: moduleHref, category: "People", description: "Employees, attendance, leave, payroll preparation, contracts, schedules, and performance reviews.", features: ["Employee records", "Payroll forwarding", "Leave approvals"] },
  { id: "finance", title: "Finance Portal", href: moduleHref, category: "Finance", description: "Revenue, payroll approvals, invoices, receipts, expenses, taxes, budgets, debts, payments, and financial reports.", features: ["Payroll approvals", "Invoices", "Budget tracking"] },
  { id: "procurement", title: "Procurement Portal", href: moduleHref, category: "Operations", description: "Suppliers, purchase requests, approvals, inventory requests, purchase orders, deliveries, and procurement reports.", features: ["Purchase requests", "Supplier records", "Purchase orders"] },
  { id: "inventory", title: "Inventory Module", href: moduleHref, category: "Inventory", description: "Stock, catalog items, transfers, warehouses, movement logs, and availability.", features: ["Stock levels", "Transfers", "Availability"] },
  { id: "retail", title: "Retail Operations Module", href: moduleHref, category: "Industry", description: "POS operations, product catalog, shelf stock, customer purchases, returns, discounts, and daily retail reports.", features: ["POS", "Returns", "Retail reports"] },
  { id: "manufacturing", title: "Manufacturing Module", href: moduleHref, category: "Industry", description: "Bills of materials, production orders, work centers, quality checks, raw materials, finished goods, and costing.", features: ["Production orders", "BOM", "Quality checks"] },
  { id: "sales", title: "Sales Portal", href: moduleHref, category: "Revenue", description: "Products, customers, orders, invoices, discounts, promotions, and revenue analytics.", features: ["Product management", "Order tracking", "Customer invoices"] },
  { id: "customer", title: "Customer Service Portal", href: moduleHref, category: "Service", description: "Support tickets, complaints, live chat, feedback, escalation, and service analytics.", features: ["Support tickets", "Complaints", "Escalation"] },
  { id: "technology", title: "Technology Services Portal", href: moduleHref, category: "Technology Services", package: "Phone Operations", description: "Phone services, repairs, devices, projects, support tickets, subscriptions, invoices, and analytics.", features: ["Phone services", "Device repairs", "Support tickets"] },
  { id: "pharmacy", title: "Pharmacy / Chemistry Portal", href: moduleHref, category: "Healthcare", description: "Medicine inventory, prescriptions, suppliers, customers, barcode scanning, returns, discounts, and pharmacy sales.", features: ["Medicine stock", "Expiry alerts", "Prescriptions"] },
  { id: "academic", title: "Academic / School Portal", href: moduleHref, category: "Education", description: "Students, fees, attendance, exams, results, timetables, teachers, and parent communication.", features: ["Students", "Fees", "Exams"] },
  { id: "hospital", title: "Hospital Portal", href: moduleHref, category: "Healthcare", description: "Patients, appointments, doctor schedules, prescriptions, billing, lab reports, nurses, and emergency records.", features: ["Patient records", "Appointments", "Billing"] },
  { id: "restaurant", title: "Restaurant Portal", href: moduleHref, category: "Hospitality", description: "Orders, kitchen dashboard, reservations, menus, staff, sales reports, and customer order tracking.", features: ["Orders", "Kitchen dashboard", "Reservations"] },
  { id: "real-estate", title: "Real Estate Portal", href: moduleHref, category: "Property", description: "Properties, tenants, rent tracking, maintenance requests, analytics, and payment records.", features: ["Property listings", "Tenants", "Rent tracking"] },
  { id: "logistics", title: "Logistics Module", href: moduleHref, category: "Operations", description: "Dispatch, delivery, fleet, routes, and shipment tracking.", features: ["Dispatch", "Tracking", "Delivery status"] },
  { id: "staff", title: "Staff Module", href: moduleHref, category: "People", description: "Role-specific staff tasks, notifications, and daily work views.", features: ["Tasks", "Notifications", "Role access"] },
  { id: "reporting", title: "Reporting Module", href: moduleHref, category: "Insights", description: "Operational, finance, audit, and organization reports with exports.", features: ["Operational reports", "Financial summaries", "Exports"] },
  { id: "analytics", title: "Analytics Module", href: moduleHref, category: "Insights", description: "Trends, charts, insights, and performance analytics.", features: ["Charts", "Insights", "Activity trends"] },
  { id: "director", title: "Executive ERP Portal", href: "Director.html", category: "Technology Services", package: "Phone Operations", description: "Executive oversight for phone services, branches, teams, agents, and approvals.", features: ["Executive reports", "Branch performance", "Approval review"] },
  { id: "device-branch", title: "Branch Operations Portal", href: "Branch.html", category: "Technology Services", package: "Phone Operations", description: "Phone branch stock, device services, clients, assets, and local sales.", features: ["Branch stock", "Phone services", "Local sales"] },
  { id: "team-leader", title: "Operations Lead Portal", href: "TeamLeader.html", category: "Technology Services", package: "Phone Operations", description: "Phone service team allocation, task assignment, service tracking, and team performance.", features: ["Agent allocation", "Task assignment", "Service tracking"] },
  { id: "agent", title: "ERP Agent Portal", href: "Agent.html", category: "Technology Services", package: "Phone Operations", description: "Phone service onboarding, clients, commissions, subscriptions, support, referrals, and reports.", features: ["Service onboarding", "Client management", "Commissions"] },
  { id: "device-departments", title: "Department Workflow Portal", href: moduleHref, category: "Technology Services", package: "Phone Operations", description: "Phone service cross-department approvals and workflow reviews.", features: ["Department access", "Approval pipelines", "Role control"] },
];

const VALID_PORTAL_IDS = new Set(PORTAL_CATALOG.map((portal) => portal.id));

module.exports = { PORTAL_CATALOG, VALID_PORTAL_IDS, moduleHref };
